neo4j:
  name: neo4j
  resources:
    cpu: "0.5"
    memory: "2Gi"
  password: "neo4jneo4j"
services:
  neo4j:
    type: ClusterIP
config:
  server.directories.plugins: "/var/lib/neo4j/labs"
  dbms.security.procedures.unrestricted: "apoc.*"
  server.config.strict_validation.enabled: "false"
  dbms.security.procedures.allowlist: "apoc.*"
volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi
apoc_config:
  apoc.trigger.enabled: "true"
  apoc.jdbc.neo4j.url: "jdbc:neo4j://neo4j-release.neo4j.svc.cluster.local:7687"
  apoc.import.file.enabled: "true"
# https://neo4j.com/docs/operations-manual/current/kubernetes/configuration/
