neo4j:
  name: neo4j
  resources:
    cpu: "0.5"
    memory: "2Gi"
  password: "neo4j"
services:
  neo4j:
    type: ClusterIP
volumes:
  data:
    mode: defaultStorageClass
    defaultStorageClass:
      requests:
        storage: 2Gi
# https://neo4j.com/docs/operations-manual/current/kubernetes/configuration/
